### ISSUE TITLE
Client-side validation of dial rename

### ISSUE THREAD

**Issue by feeph** [SasaKaranovic/VU-Server#11]
It looks like VUServer WebGUI silently rejects some input.

observed behavior:

1) open a dial settings page (http://localhost:5340/index.html?page=dial&uid=...)
2) enter name `#1` or `'1` and save
3) this page is now updated and shows `Name: #1`
4) go to the overview page listing (http://localhost:5340/)
5) the name has not changed and still shows the previously configured value

desired behavior:

- When trying to set an invalid character the 'save' operation should fail and the dial page should preserve the current value.

There seems to be a limited number of characters that will not be accepted. # and ' will fail while " does not fail. I don't want to argue that these 2 characters must be included, but I would like to argue that the software shouldn't pretend to have done something when in fact it didn't.

I think the issue can be traced to https://github.com/SasaKaranovic/VU-Server/blob/ee237b6d6842b43d927727743737e846b1415b53/www/assets/js/vu1_gui_dial.js#L100
The JavaScript code makes an API call to `/api/v0/dial/<dial_uid>/name` but does not verify whether the API call was successful.

OS: Windows 11
VUServer version: v20240110

**Comment by SasaKaranovic** [comment]
Hi @feeph

Thank you for reporting this.
I'll rename this issue and we can keep track of progress here.

**Comment by feeph** [comment]
Thanks for acknowledging the 3 issues I filed. Please take them as a positive sign and encouragement. I care about the project and I want it to succeed.

I was waiting for these dials since Gamers Nexus featured them last year and I'm so happy I finally am able to get my hands onto them. Bumps on the road are expected with something so novel and despite them I really like what I see so far.

**Comment by SasaKaranovic** [comment]
Hey @feeph ! Thank you for taking the time to report them! We appreciate it.
And I hope that you are able to enjoy the VU Dials even if everything may not be perfect out of the box.

We are (becoming?) aware that we have created something as you said 'novel'. 
Maybe not so much when you look at any single piece on it's own, but maybe when you look at the big picture. 
This product is built by enthusiasts for enthusiasts. There will be growing pains but we are hoping that as the end result, we eventually have the product that the community loves and is also shaped by the feedback and contributions from the community.
