### ISSUE TITLE
Linux: Cannot update dial name

### ISSUE THREAD

**Issue by thamarnan** [SasaKaranovic/VU-Server#13]
When try curl update dial name
it says status ok
but when query it again,

dial_name: "Not Set"

```

user@portainer:~/vudial$ curl  "http://localhost:5340/api/v0/dial/3C006B650564139323920/set?key=cTpAWYuRpA2zxh961Cg&name=abc"
{"status": "ok", "message": "Update queued", "data": null}user@portainer:~/vudial$ 
user@portainer:~/vudial$ 
user@portainer:~/vudial$ curl  "http://localhost:5340/api/v0/dial/list?key=cTpAWYuRpA2zx75Yh961Cg"
{"status": "ok", "message": "", "data": [{"uid": "4C0031000650139323920", "dial_name": "Not set", "value": 0, "backlight": {"red": 0, "green": 0, "blue": 0}, "image_file": "img_blank"}, {"uid": "3C006B000650564133920", "dial_name": "Not set", "value": 0, "backlight": {"red": 0, "green": 22, "blue": 33}, "image_file": "img_blank"}]}user@portainer:~/vudial$ 
user@portainer:~/vudial$ 
user@portainer:~/vudial$ 

##also try different method
user@portainer:~/vudial$ curl -d "name=abc"-X POST "http://localhost:5340/api/v0/dial/3C006B000664139323920/set?key=cTpAWYuRzx75Yh961Cg"
curl: (6) Could not resolve host: POST
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/tornado/web.py", line 269, in _unimplemented_method
    raise HTTPError(405)
tornado.web.HTTPError: HTTP 405: Method Not Allowed

```

**Comment by SasaKaranovic** [comment]
@thamarnan Can you double check if you maybe have a typo or if you are targeting the correct `DIAL_UID`?

In the `curl` you are referencing`3C006B650564139323920` as DIAL_UID.
But in your `/dial/list` that dial does not exist, only the `3C006B000650564133920` and  `4C0031000650139323920`

**Comment by thamarnan** [comment]
Ok i found the problem.
The UID is fine. I was redacted.
I use Fiddler to see the command send from dashboard
it's using "/name" not "/set" 

so just need to fix documentation
https://docs.vudials.com/api/dial_UID_name/

**Comment by SasaKaranovic** [comment]
Hey @thamarnan, thank you for reporting this!

Actually I owe you an apology because the API documentation has a typo (copy&paste issue).
So even if you have followed it, you will not get the desired result.

It should be fixed now with the [latest](https://github.com/SasaKaranovic/VU-Documentation/commit/697711381c0524e990e8565d588060b655764731) commit.
