### ISSUE TITLE
Server does not identify properly slave meters

### ISSUE THREAD

**Issue by dj-dule** [SasaKaranovic/VU-Server#25]
I purchased pack of 4 meters, hub and 3 slaves and connected them as instructed (computer to hub and then 3 slaves daisy chained using provided cables). After building and running server it seems all 4 of them are identified properly, or at least I see all of them from webUI. I can properly indentify hub using "Identify dial" function. But when I use same function on any of the slaves all 3 are activated at the same time. It happens when I try to identify any of them. Any idea what is wrong ?

**Comment by SasaKaranovic** [comment]
Hi @dj-dule 

Can you please try the suggestion from the FAQ (https://vudials.com/)
There is an entry called `I just added all my Dials but they seem to be outputting the same data, how do I solve that?`

**Comment by dj-dule** [comment]
That helped thanks, disconnected them and then attached one by one. It works now
