### ISSUE TITLE
Blocked by Riot Vanguard

### ISSUE THREAD

**Issue by PureDriveGT** [SasaKaranovic/VU-Server#27]
Sadly the Server App gets blocked by Riot Vanguard (for League of Legends, Valorant...) making it unusable for me, is there a way to get this software whitelisted for Vanguard?

**Comment by SasaKaranovic** [comment]
Hi @PureDriveGT 

Does Riot Vanguard support white listing applications?
I assume this is something that would need to happen on the Riot Vanguard side. Have you tried reaching out to their support team and asking how to address this issue?

**Comment by PureDriveGT** [comment]
hey, thanks for the reply, just wanted to let you know that the app is no longer blocked by Vanguard.
