### ISSUE TITLE
No license info?

### ISSUE THREAD

**Issue by bjowi** [SasaKaranovic/VU-Server#39]
Hello, there doesn't seem to be a license set for the code in this repo. Is the code open source?

**Comment by SasaKaranovic** [comment]
Great question! It is stated multiple times through the project/forum/media that the code is open source. So yes.

**Comment by brianclemens** [comment]
@SasaKaranovic a proper license would be very helpful, just stating that something is open source isn't useful. Licenses protect both users and authors. If someone wants to build and sell a solution using VU1 meters, they can't bundle this software with it without opening themselves up to liabilities. And without a disclaimer of liability, putting this code out opens you up to frivolous lawsuits.

Love the meters, and it's great that the server source code is public, but it's not really open source unless it includes an [OSI Approved License](https://opensource.org/licenses).

(I run a large [open source software foundation](https://resf.org) and [project](https://rockylinux.org) so I know a little bit about licensing. Would recommend either BSD 3 Clause or the MIT license, which are functionally equivalent.)

**Comment by thejevans** [comment]
Just commenting here to clarify that, without a specific license, all software is considered all-rights-reserved under copyright law for all countries that are signatories of the Berne Convention (this is most countries) and is explicitly not open-source. Open-source is about copyright first and viewing code second. Calling something open-source on your website does not make it so.
