### ISSUE TITLE
Red and green colours swapped on hub device

### ISSUE THREAD

**Issue by bjowi** [SasaKaranovic/VU-Server#40]
I'm testing with a hub and a few dials, and the hub device seems to have its red/green values swapped. 
I can verify it in the web interface, and also by calling dial_set_backlight directly.

The non-hub dials behave as expected.

I'm running on latest master.

**Comment by SasaKaranovic** [comment]
Hey @bjowi ! This does not look like a software issue so please reach out to Streacom support directly to help you get this issue resolved.
