### ISSUE TITLE
Unable to start server app - Access to serial port denied

### ISSUE THREAD

**Issue by PlasticGhoul** [SasaKaranovic/VU-Server#42]
I'm not able to start the VU Server application due to the error:

> VU Server failed to start. Access to serial port denied. VU Server already running?

The log file says the following:

> 2024-04-30 18:08:44,199 INFO set_logger_level(62) Logging level: INFO
> 2024-04-30 18:08:44,200 INFO __init__(528) Loading server config...
> 2024-04-30 18:08:44,200 INFO __init__(21) VU1 config yaml file: C:\Program Files (x86)\KaranovicResearch\VUDials\_internal\config.yaml
> 2024-04-30 18:08:44,200 INFO __init__(18) VU1 Database file: C:\Program Files (x86)\KaranovicResearch\VUDials\_internal\vudials.db
> 2024-04-30 18:08:44,211 INFO __init__(546) VU1 HUB port: COM1 - USB Serial Port (COM1)
> 2024-04-30 18:08:44,212 ERROR main(658) VU Dials API service - Serial port access denied
> Traceback (most recent call last):
>   File "server.py", line 656, in main
>   File "server.py", line 547, in __init__
>   File "dial_driver.py", line 20, in __init__
>   File "serial_driver.py", line 36, in __init__
>   File "serial\serialwin32.py", line 33, in __init__
>   File "serial\serialutil.py", line 244, in __init__
>   File "serial\serialwin32.py", line 64, in open
> serial.serialutil.SerialException: could not open port 'COM1': PermissionError(13, 'Zugriff verweigert', None, 5)

I already checked that no ports are being used. The API port and the COM port are all clear.
Also no process is using the COM port as far as I am aware - I checked with SysInternals Process Explorer
What am I missing?

**Comment by PlasticGhoul** [comment]
It turns out that SignalRGB is the source of the problem. If I kill the SignalRGB process, the VU Server is starting - Not sure why though

**Comment by SasaKaranovic** [comment]
Hi @PlasticGhoul 
Thank you for reporting this! 
SignalRGB is not open source so we can't take a look at it but my guess would be that SignalRGB for some reason erroneously identifies VU hub as one of the supported RGB devices and tries to configure it.
I would suggest opening a support ticket with them and letting them know about this issue.
