### ISSUE TITLE
Created a subreddit for discussion

### ISSUE THREAD

**Issue by extreme-sysadminning** [SasaKaranovic/VU-Server#5]
I created a subreddit for discussion, showing off dials, asking for help or helping others:
https://www.reddit.com/r/vudials/

I'll also create a wiki later where interested people can upload their backgrounds, scripts or commands, everything that isn't exactly github material and that would end up unread otherwise.

My ideas for the dials:

- I plan to create a script that fetches gold and ETF prices and tells me if it's a good price to buy or sell compared to a 200day average and maybe to my own holdings and buying prices. Something like dial-position and color of the background will be visual queues.
- I also plan to use it for Zabbix, maybe show the amount and severity of problems or something.
- Finally i need a dial that tells me if i need an umbrella or sunhat on my way to work.

**Comment by SasaKaranovic** [comment]
Hi @extreme-sysadminning

We appreciate the effort you put into this.

Please keep in mind that we have the VU Dials forum that is dedicated to the VU Dials community and will be made available to the general public very soon!
