### ISSUE TITLE
Include a Linux distributable package

### ISSUE THREAD

**Issue by hawkw** [SasaKaranovic/VU-Server#8]
Hi, I'd like to package `VU-Server` for my Linux distro's package manager. The recommended way of packaging a Python application on my distro involves using a `setuptools` [`setup.py` file](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/). Therefore, I'd love it if this repo could include such a file.

I'd be happy to open a PR adding one, if the authors are interested in merging it!

**Comment by SasaKaranovic** [comment]
Hi @hawkw 

Thank you for the great suggestion!
I think this would be a great addition for Linux users.

Please feel free to open a PR for this issue and we can collaborate on it.

**Comment by hawkw** [comment]
Hmm, if I understand [the documentation for setuptools](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#automatic-discovery) correctly (and it's possible I don't, I'm not particularly familiar with Python), it looks like `setuptools` expects the package code to live in a subdirectory, either `src/<packagename>/` or `<packagename>/`. Would you mind if I move the package source into a `vu-server` subdirectory as part of a PR adding setuptools support?

**Comment by SasaKaranovic** [comment]
It might make more sense to actually build a "distributable" app using pyinstaller like we do for Windows.

This is actually the preferred way in my opinion. Because people would not have to have Python, Pip/setuptools or anything else installed. They would just be able to run/install the binary and they are good to go.

**Comment by hawkw** [comment]
I'm also fine with that, although I'm not personally familiar with how to use `pyinstaller`. Mainly, I'd just like to have any way to run VU-Server without `pip install`ing its dependencies into my system's global Python environment, so I'd be happy with any way of distributing the server for Linux that works for you. Happy to help out setting it up.

**Comment by SasaKaranovic** [comment]
Currently we use `pyinstaller` to compile server application for Windows ([GitHub Action](https://github.com/SasaKaranovic/VU-Server/blob/master/.github/workflows/pyinstaller.yaml#L53)).

We could use the same process for Linux and distribute the executable archive.

> I'd just like to have any way to run VU-Server without pip installing its dependencies into my system's global Python environment

You (and other developers) could use python virtual environment (`venv`, `pyvenv` etc). But this should not be the way regular users consume the application.

I was a bit confused by the `setup.py` suggestion but now I think I better understand what you are suggesting and `pyinstaller` is probably the way forward. I'll rename this issue to `Linux distributable package` so it's clear what we are looking for and we can track the progress here.
